baseurl = "http://blog.terrywh.net/"
languageCode = "zh-cn"
title = "Hello World"
theme = "hugo-tranquilpeak-theme"
publishDir = "../blog"
defaultContentLanguage = "zh-cn"

[params]
  description = "Web Development by Go/Nodejs/PHP/C++"
  disqusShortname = "terrywh"